#!/bin/bash

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then

        echo 'graph_title nasune status'
        echo 'graph_args  -l 0'
        #echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel byte'

        #echo 'graph_scale no'
        echo 'graph_category nasune'
        echo 'graph_info nasune status'

        echo 'rec.label Rec'
        echo 'rec.draw AREA'
        echo 'rec.colour EB0020'
        echo 'play.label Play'
        echo 'play.draw AREA'
        echo 'play.colour 008040'
        echo 'live.label Live'
        echo 'live.draw STACK'
        echo 'live.colour FF8000'

        # Last, if run with the "config"-parameter, quit here (don't
        # display any data)
        exit 0
fi


/usr/local/bin/nasune_status.pl

