#!/bin/bash

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then

        echo 'graph_title nasune disk usage'
        echo 'graph_args  -l 0'
        #echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel byte'

        #echo 'graph_scale no'
        echo 'graph_category nasune'
        echo 'graph_info nasune disk usage graph'

        echo 'used.label HDD used'
        echo 'used.info usedVolumeSize'
        echo 'used.draw AREA'
        echo 'free.label HDD free'
        echo 'free.info freeVolumeSize'
        echo 'free.draw STACK'

        # Last, if run with the "config"-parameter, quit here (don't
        # display any data)
        exit 0
fi


/usr/local/bin/nasune_hdd.pl

